In [7]:
class Employee:

    employee_count = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    @classmethod
    def average_salary(cls, employees):
        total_salary = sum(employee.salary for employee in employees)
        return total_salary / cls.employee_count if cls.employee_count > 0 else 0

    @staticmethod
    def employee_info(employee):
        return f"Name: {employee.name}, Family: {employee.family}, Salary: {employee.salary}, Department: {employee.department}"


class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, benefits):
        super().__init__(name, family, salary, department)
        self.benefits = benefits

    def fulltime_employee_info(self):
        return f"{super().employee_info(self)}, Benefits: {self.benefits}"


emp1 = Employee("Sri", "Durga", 40000, "Dept")
emp2 = Employee("Sai", "Krishna", 70000, "IT")
emp3 = FulltimeEmployee("Subash", "Bhagwan", 80000, "Software", "Insurance")
emp4 = FulltimeEmployee("Rohith", "Nirva", 160000, "Hardware", "Manfracturing")

employees = [emp1, emp2, emp3, emp4]


print(Employee.employee_info(emp1))
print(Employee.employee_info(emp2))
print(emp3.fulltime_employee_info())
print(emp4.fulltime_employee_info())


average_salary = Employee.average_salary(employees)
print(f"Average Salary: ${average_salary:.2f}")


print(f"Total number of Employees: {Employee.employee_count}")


Name: Sri, Family: Durga, Salary: 40000, Department: Dept
Name: Sai, Family: Krishna, Salary: 70000, Department: IT
Name: Subash, Family: Bhagwan, Salary: 80000, Department: Software, Benefits: Insurance
Name: Rohith, Family: Nirva, Salary: 160000, Department: Hardware, Benefits: Manfracturing
Average Salary: $87500.00
Total number of Employees: 4


In [9]:
import numpy as np

vector = np.random.uniform(1, 20, size=20)

array = vector.reshape(4, 5)

mask = array == np.max(array, axis=1, keepdims=True)

array[mask] = 0

print("Final Array is")
print(array)


Final Array is
[[ 0.         11.3104193   8.26817506  5.85037952  2.88175464]
 [16.58929998  9.64469325  0.         11.81613707  8.65457973]
 [17.56846574 13.2712494   6.60524534  0.          6.25396992]
 [ 1.93802762  3.0352358   6.21417617 11.96330052  0.        ]]
